"""tenant scheduler reports and analytics

Revision ID: 20260804_0006
Revises: 20260804_0005
Create Date: 2026-08-04 19:16:38.362329
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260804_0006"
down_revision: str | None = "20260804_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_health",
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runtime_health", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runtime_health_component"), ["component"], unique=True)
        batch_op.create_index(batch_op.f("ix_runtime_health_status"), ["status"], unique=False)

    op.create_table(
        "departments",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_department_name"),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_departments_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_departments_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "tenant_analysis_schedules",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("report_time", sa.Time(), nullable=False),
        sa.Column("enabled_days", sa.JSON(), nullable=False),
        sa.Column("history_window_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column("advance_minutes", sa.Integer(), server_default="10", nullable=False),
        sa.Column("analysis_enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("next_analysis_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_analysis_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_completed_report_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_enqueued_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("grace_period_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("advance_minutes IN (5,10,15,30)", name="ck_schedule_advance"),
        sa.CheckConstraint("history_window_days IN (3,7,14,30)", name="ck_schedule_history"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenant_analysis_schedules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tenant_analysis_schedules_access_expires_at"),
            ["access_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_analysis_schedules_access_status"),
            ["access_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_analysis_schedules_analysis_enabled"),
            ["analysis_enabled"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_analysis_schedules_next_analysis_at"),
            ["next_analysis_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_analysis_schedules_tenant_id"), ["tenant_id"], unique=True
        )

    op.create_table(
        "tenant_daily_metrics",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "metric_date", name="uq_tenant_daily"),
    )
    with op.batch_alter_table("tenant_daily_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tenant_daily_metrics_metric_date"), ["metric_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_daily_metrics_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "tenant_queue_states",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("last_claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_heavy_jobs", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenant_queue_states", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tenant_queue_states_last_claimed_at"), ["last_claimed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_queue_states_tenant_id"), ["tenant_id"], unique=True
        )

    op.create_table(
        "employees",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employees_department_id"), ["department_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_employees_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "analysis_runs",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_account_id", sa.String(length=36), nullable=True),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="queued", nullable=False),
        sa.Column("stage", sa.String(length=64), server_default="queued", nullable=False),
        sa.Column("report_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delayed_reason", sa.String(length=200), nullable=True),
        sa.Column("required_batches", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completed_batches", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_batches", sa.Integer(), server_default="0", nullable=False),
        sa.Column("token_budget", sa.Integer(), server_default="50000", nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telegram_account_id"], ["telegram_connections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_runs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analysis_runs_report_due_at"), ["report_due_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_runs_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analysis_runs_telegram_account_id"),
            ["telegram_account_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_analysis_runs_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_runs_trigger"), ["trigger"], unique=False)

    op.create_table(
        "employee_daily_metrics",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "metric_date", name="uq_employee_daily"),
    )
    with op.batch_alter_table("employee_daily_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employee_daily_metrics_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_employee_daily_metrics_metric_date"), ["metric_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_employee_daily_metrics_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "employee_roles",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "role", name="uq_employee_role"),
    )
    with op.batch_alter_table("employee_roles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employee_roles_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_employee_roles_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "employee_telegram_accounts",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "telegram_user_id", name="uq_employee_telegram"),
    )
    with op.batch_alter_table("employee_telegram_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_employee_telegram_accounts_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_employee_telegram_accounts_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "sync_metrics",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["connection_id"], ["telegram_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "metric_date", name="uq_sync_daily"),
    )
    with op.batch_alter_table("sync_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_metrics_connection_id"), ["connection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sync_metrics_metric_date"), ["metric_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sync_metrics_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "tenant_memberships",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("employee_id", sa.String(length=36), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "telegram_user_id", name="uq_tenant_membership"),
    )
    with op.batch_alter_table("tenant_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tenant_memberships_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tenant_memberships_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_tenant_memberships_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tenant_memberships_telegram_user_id"), ["telegram_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tenant_memberships_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "ai_usage_metrics",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=True),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("request_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("recheck_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("discarded_candidates", sa.Integer(), server_default="0", nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "metric_date", "model", name="uq_ai_usage_daily_model"),
    )
    with op.batch_alter_table("ai_usage_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_usage_metrics_analysis_run_id"), ["analysis_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_usage_metrics_metric_date"), ["metric_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_usage_metrics_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "analysis_batches",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("dialog_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.String(length=16), server_default="1.0", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("route_name", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("local_features_json", sa.JSON(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("raw_response_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("repair_attempted", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dialog_id"], ["telegram_dialogs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "dialog_id", name="uq_analysis_batch_run_dialog"),
    )
    with op.batch_alter_table("analysis_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_batches_dialog_id"), ["dialog_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_batches_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_batches_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analysis_batches_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "chat_daily_metrics",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("dialog_id", sa.String(length=36), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dialog_id"], ["telegram_dialogs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dialog_id", "metric_date", name="uq_chat_daily"),
    )
    with op.batch_alter_table("chat_daily_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_daily_metrics_dialog_id"), ["dialog_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_daily_metrics_metric_date"), ["metric_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_daily_metrics_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "permissions",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("membership_id", sa.String(length=36), nullable=False),
        sa.Column("permission", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["membership_id"], ["tenant_memberships.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("membership_id", "permission", name="uq_membership_permission"),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_permissions_membership_id"), ["membership_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_permissions_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="forming", nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "delivery_status", sa.String(length=32), server_default="pending", nullable=False
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reports_analysis_run_id"), ["analysis_run_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_reports_delivery_status"), ["delivery_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_reports_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "report_generation_runs",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delayed_reason", sa.String(length=200), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report_generation_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_generation_runs_report_id"), ["report_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_report_generation_runs_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_report_generation_runs_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "report_metrics",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("metric_key", sa.String(length=64), nullable=False),
        sa.Column("numeric_value", sa.Float(), server_default="0", nullable=False),
        sa.Column("data_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "metric_key", name="uq_report_metric"),
    )
    with op.batch_alter_table("report_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_metrics_report_id"), ["report_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_report_metrics_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "report_sections",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("section_key", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("data_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "section_key", name="uq_report_section"),
    )
    with op.batch_alter_table("report_sections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_sections_report_id"), ["report_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_report_sections_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "report_problems",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["problem_id"], ["operational_problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "problem_id", name="uq_report_problem"),
    )
    with op.batch_alter_table("report_problems", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_report_problems_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_report_problems_report_id"), ["report_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_report_problems_tenant_id"), ["tenant_id"], unique=False
        )

    with op.batch_alter_table("background_jobs", schema=None) as batch_op:
        batch_op.drop_constraint("ck_background_jobs_status", type_="check")
        batch_op.add_column(sa.Column("telegram_account_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("correlation_id", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("progress_json", sa.JSON(), server_default="{}", nullable=False)
        )
        batch_op.add_column(sa.Column("is_heavy", sa.Boolean(), server_default="0", nullable=False))
        batch_op.add_column(
            sa.Column("category", sa.String(length=32), server_default="general", nullable=False)
        )
        batch_op.add_column(sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("delay_reason", sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f("ix_background_jobs_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_background_jobs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(
            "ix_background_jobs_fair_claim",
            ["status", "priority", "scheduled_at", "tenant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_background_jobs_heartbeat_at"), ["heartbeat_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_background_jobs_is_heavy"), ["is_heavy"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_background_jobs_telegram_account_id"),
            ["telegram_account_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_background_jobs_telegram_account",
            "telegram_connections",
            ["telegram_account_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_check_constraint(
            "ck_background_jobs_status",
            "status IN ('pending','scheduled','running','waiting','retry','retry_scheduled',"
            "'completed','failed','cancelled')",
        )

    with op.batch_alter_table("telegram_connections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "health_status", sa.String(length=32), server_default="unknown", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("selected_folder_ids", sa.JSON(), server_default="[]", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_telegram_connections_health_status"), ["health_status"], unique=False
        )

    with op.batch_alter_table("tenant_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("analysis_enabled", sa.Boolean(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column("analysis_advance_minutes", sa.Integer(), server_default="10", nullable=False)
        )
        batch_op.add_column(
            sa.Column("enabled_days", sa.JSON(), server_default="[0,1,2,3,4]", nullable=False)
        )
        batch_op.add_column(
            sa.Column("history_window_days", sa.Integer(), server_default="7", nullable=False)
        )
        batch_op.create_check_constraint(
            "ck_tenant_settings_analysis_advance",
            "analysis_advance_minutes IN (5,10,15,30)",
        )
        batch_op.create_check_constraint(
            "ck_tenant_settings_history_window",
            "history_window_days IN (3,7,14,30)",
        )

    op.execute(
        "INSERT INTO tenant_memberships "
        "(id, tenant_id, telegram_user_id, role, status, created_at, updated_at) "
        "SELECT lower(hex(randomblob(16))), id, owner_telegram_user_id, 'owner', 'active', "
        "CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM tenants"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenant_settings", schema=None) as batch_op:
        batch_op.drop_constraint("ck_tenant_settings_history_window", type_="check")
        batch_op.drop_constraint("ck_tenant_settings_analysis_advance", type_="check")
        batch_op.drop_column("history_window_days")
        batch_op.drop_column("enabled_days")
        batch_op.drop_column("analysis_advance_minutes")
        batch_op.drop_column("analysis_enabled")

    with op.batch_alter_table("telegram_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_connections_health_status"))
        batch_op.drop_column("health_status")
        batch_op.drop_column("last_health_check_at")
        batch_op.drop_column("selected_folder_ids")

    with op.batch_alter_table("background_jobs", schema=None) as batch_op:
        batch_op.drop_constraint("ck_background_jobs_status", type_="check")
        batch_op.drop_constraint("fk_background_jobs_telegram_account", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_background_jobs_telegram_account_id"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_is_heavy"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_heartbeat_at"))
        batch_op.drop_index("ix_background_jobs_fair_claim")
        batch_op.drop_index(batch_op.f("ix_background_jobs_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_category"))
        batch_op.drop_column("delay_reason")
        batch_op.drop_column("heartbeat_at")
        batch_op.drop_column("category")
        batch_op.drop_column("is_heavy")
        batch_op.drop_column("progress_json")
        batch_op.drop_column("correlation_id")
        batch_op.drop_column("telegram_account_id")
        batch_op.create_check_constraint(
            "ck_background_jobs_status",
            "status IN ('pending','running','completed','failed','retry_scheduled','cancelled')",
        )

    with op.batch_alter_table("report_problems", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_problems_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_report_problems_report_id"))
        batch_op.drop_index(batch_op.f("ix_report_problems_problem_id"))

    op.drop_table("report_problems")
    with op.batch_alter_table("report_sections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_sections_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_report_sections_report_id"))

    op.drop_table("report_sections")
    with op.batch_alter_table("report_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_metrics_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_report_metrics_report_id"))

    op.drop_table("report_metrics")
    with op.batch_alter_table("report_generation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_generation_runs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_report_generation_runs_status"))
        batch_op.drop_index(batch_op.f("ix_report_generation_runs_report_id"))

    op.drop_table("report_generation_runs")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_reports_status"))
        batch_op.drop_index(batch_op.f("ix_reports_delivery_status"))
        batch_op.drop_index(batch_op.f("ix_reports_analysis_run_id"))

    op.drop_table("reports")
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_permissions_membership_id"))

    op.drop_table("permissions")
    with op.batch_alter_table("chat_daily_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_daily_metrics_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_chat_daily_metrics_metric_date"))
        batch_op.drop_index(batch_op.f("ix_chat_daily_metrics_dialog_id"))

    op.drop_table("chat_daily_metrics")
    with op.batch_alter_table("analysis_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_batches_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_batches_status"))
        batch_op.drop_index(batch_op.f("ix_analysis_batches_run_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_batches_dialog_id"))

    op.drop_table("analysis_batches")
    with op.batch_alter_table("ai_usage_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_usage_metrics_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_metrics_metric_date"))
        batch_op.drop_index(batch_op.f("ix_ai_usage_metrics_analysis_run_id"))

    op.drop_table("ai_usage_metrics")
    with op.batch_alter_table("tenant_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_memberships_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_memberships_telegram_user_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_memberships_status"))
        batch_op.drop_index(batch_op.f("ix_tenant_memberships_role"))
        batch_op.drop_index(batch_op.f("ix_tenant_memberships_employee_id"))

    op.drop_table("tenant_memberships")
    with op.batch_alter_table("sync_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_metrics_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_sync_metrics_metric_date"))
        batch_op.drop_index(batch_op.f("ix_sync_metrics_connection_id"))

    op.drop_table("sync_metrics")
    with op.batch_alter_table("employee_telegram_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employee_telegram_accounts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_employee_telegram_accounts_employee_id"))

    op.drop_table("employee_telegram_accounts")
    with op.batch_alter_table("employee_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employee_roles_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_employee_roles_employee_id"))

    op.drop_table("employee_roles")
    with op.batch_alter_table("employee_daily_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employee_daily_metrics_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_employee_daily_metrics_metric_date"))
        batch_op.drop_index(batch_op.f("ix_employee_daily_metrics_employee_id"))

    op.drop_table("employee_daily_metrics")
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_runs_trigger"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_telegram_account_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_status"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_report_due_at"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_correlation_id"))

    op.drop_table("analysis_runs")
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_employees_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_employees_department_id"))

    op.drop_table("employees")
    with op.batch_alter_table("tenant_queue_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_queue_states_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_queue_states_last_claimed_at"))

    op.drop_table("tenant_queue_states")
    with op.batch_alter_table("tenant_daily_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_daily_metrics_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_daily_metrics_metric_date"))

    op.drop_table("tenant_daily_metrics")
    with op.batch_alter_table("tenant_analysis_schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_analysis_schedules_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_analysis_schedules_next_analysis_at"))
        batch_op.drop_index(batch_op.f("ix_tenant_analysis_schedules_analysis_enabled"))
        batch_op.drop_index(batch_op.f("ix_tenant_analysis_schedules_access_status"))
        batch_op.drop_index(batch_op.f("ix_tenant_analysis_schedules_access_expires_at"))

    op.drop_table("tenant_analysis_schedules")
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_departments_parent_id"))

    op.drop_table("departments")
    with op.batch_alter_table("runtime_health", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runtime_health_status"))
        batch_op.drop_index(batch_op.f("ix_runtime_health_component"))

    op.drop_table("runtime_health")
    # ### end Alembic commands ###
